config/routes.rb
Dregs::Application.routes.draw do
  resources :tokens

  resources :commands

  resources :users

end

app/models/command.rb
class Command < ActiveRecord::Base
  belongs_to :user
  attr_accessible :ran_at, :str
	has_many :tokens

	def save_tokens
		token_strs = self.str.split( /\s+/ )  
		token_strs.each_with_index do |token_str,i|
			self.tokens.create( :position => i, :str => token_str ) 
		end
	end

end

app/models/token.rb
class Token < ActiveRecord::Base
  belongs_to :command
  attr_accessible :position, :str
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :handle, :passcode

	has_many :commands
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/commands_controller.rb
class CommandsController < ApplicationController
  # GET /commands
  # GET /commands.json
  def index
    @commands = Command.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @commands }
    end
  end

  # GET /commands/1
  # GET /commands/1.json
  def show
    @command = Command.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @command }
    end
  end

  # GET /commands/new
  # GET /commands/new.json
  def new
    @command = Command.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @command }
    end
  end

  # GET /commands/1/edit
  def edit
    @command = Command.find(params[:id])
  end

  # POST /commands
  # POST /commands.json
  def create
    @command = Command.new(params[:command])

    respond_to do |format|
      if @command.save
        format.html { redirect_to @command, :notice => 'Command was successfully created.' }
        format.json { render :json => @command, :status => :created, :location => @command }
      else
        format.html { render :action => "new" }
        format.json { render :json => @command.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /commands/1
  # PUT /commands/1.json
  def update
    @command = Command.find(params[:id])

    respond_to do |format|
      if @command.update_attributes(params[:command])
        format.html { redirect_to @command, :notice => 'Command was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @command.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /commands/1
  # DELETE /commands/1.json
  def destroy
    @command = Command.find(params[:id])
    @command.destroy

    respond_to do |format|
      format.html { redirect_to commands_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/tokens_controller.rb
class TokensController < ApplicationController
  # GET /tokens
  # GET /tokens.json
  def index
    @tokens = Token.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @tokens }
    end
  end

  # GET /tokens/1
  # GET /tokens/1.json
  def show
    @token = Token.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @token }
    end
  end

  # GET /tokens/new
  # GET /tokens/new.json
  def new
    @token = Token.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @token }
    end
  end

  # GET /tokens/1/edit
  def edit
    @token = Token.find(params[:id])
  end

  # POST /tokens
  # POST /tokens.json
  def create
    @token = Token.new(params[:token])

    respond_to do |format|
      if @token.save
        format.html { redirect_to @token, :notice => 'Token was successfully created.' }
        format.json { render :json => @token, :status => :created, :location => @token }
      else
        format.html { render :action => "new" }
        format.json { render :json => @token.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /tokens/1
  # PUT /tokens/1.json
  def update
    @token = Token.find(params[:id])

    respond_to do |format|
      if @token.update_attributes(params[:token])
        format.html { redirect_to @token, :notice => 'Token was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @token.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /tokens/1
  # DELETE /tokens/1.json
  def destroy
    @token = Token.find(params[:id])
    @token.destroy

    respond_to do |format|
      format.html { redirect_to tokens_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, :notice => 'User was successfully created.' }
        format.json { render :json => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.json { render :json => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, :notice => 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/commands_helper.rb
module CommandsHelper
end

app/helpers/tokens_helper.rb
module TokensHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/commands/_form.html.erb
<%= form_for(@command) do |f| %>
  <% if @command.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@command.errors.count, "error") %> prohibited this command from being saved:</h2>

      <ul>
      <% @command.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user %><br />
    <%= f.text_field :user %>
  </div>
  <div class="field">
    <%= f.label :str %><br />
    <%= f.text_field :str %>
  </div>
  <div class="field">
    <%= f.label :ran_at %><br />
    <%= f.datetime_select :ran_at %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/commands/edit.html.erb
<h1>Editing command</h1>

<%= render 'form' %>

<%= link_to 'Show', @command %> |
<%= link_to 'Back', commands_path %>

app/views/commands/index.html.erb
<h1>Listing commands</h1>

<table>
  <tr>
    <th>User</th>
    <th>Str</th>
    <th>Ran at</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @commands.each do |command| %>
  <tr>
    <td><%= command.user %></td>
    <td><%= command.str %></td>
    <td><%= command.ran_at %></td>
    <td><%= link_to 'Show', command %></td>
    <td><%= link_to 'Edit', edit_command_path(command) %></td>
    <td><%= link_to 'Destroy', command, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Command', new_command_path %>

app/views/commands/new.html.erb
<h1>New command</h1>

<%= render 'form' %>

<%= link_to 'Back', commands_path %>

app/views/commands/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @command.user %>
</p>

<p>
  <b>Str:</b>
  <%= @command.str %>
</p>

<p>
  <b>Ran at:</b>
  <%= @command.ran_at %>
</p>


<%= link_to 'Edit', edit_command_path(@command) %> |
<%= link_to 'Back', commands_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dregs</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tokens/_form.html.erb
<%= form_for(@token) do |f| %>
  <% if @token.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@token.errors.count, "error") %> prohibited this token from being saved:</h2>

      <ul>
      <% @token.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :command %><br />
    <%= f.text_field :command %>
  </div>
  <div class="field">
    <%= f.label :str %><br />
    <%= f.text_field :str %>
  </div>
  <div class="field">
    <%= f.label :position %><br />
    <%= f.number_field :position %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tokens/edit.html.erb
<h1>Editing token</h1>

<%= render 'form' %>

<%= link_to 'Show', @token %> |
<%= link_to 'Back', tokens_path %>

app/views/tokens/index.html.erb
<h1>Listing tokens</h1>

<table>
  <tr>
    <th>Command</th>
    <th>Str</th>
    <th>Position</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tokens.each do |token| %>
  <tr>
    <td><%= token.command %></td>
    <td><%= token.str %></td>
    <td><%= token.position %></td>
    <td><%= link_to 'Show', token %></td>
    <td><%= link_to 'Edit', edit_token_path(token) %></td>
    <td><%= link_to 'Destroy', token, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Token', new_token_path %>

app/views/tokens/new.html.erb
<h1>New token</h1>

<%= render 'form' %>

<%= link_to 'Back', tokens_path %>

app/views/tokens/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Command:</b>
  <%= @token.command %>
</p>

<p>
  <b>Str:</b>
  <%= @token.str %>
</p>

<p>
  <b>Position:</b>
  <%= @token.position %>
</p>


<%= link_to 'Edit', edit_token_path(@token) %> |
<%= link_to 'Back', tokens_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :handle %><br />
    <%= f.text_field :handle %>
  </div>
  <div class="field">
    <%= f.label :passcode %><br />
    <%= f.text_field :passcode %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Email</th>
    <th>Handle</th>
    <th>Passcode</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.email %></td>
    <td><%= user.handle %></td>
    <td><%= user.passcode %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
  <b>Handle:</b>
  <%= @user.handle %>
</p>

<p>
  <b>Passcode:</b>
  <%= @user.passcode %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>